image: openjdk:11-jdk

# Disable the Gradle daemon for Continuous Integration servers as correctness
# is usually a priority over speed in CI environments. Using a fresh
# runtime for each build is more reliable since the runtime is completely
# isolated from any previous builds.
variables:
  GRADLE_OPTS: "-Dorg.gradle.daemon=false"

cache:
  paths:
    - .gradle

before_script:
  - export GRADLE_USER_HOME=`pwd`/.gradle

stages:
  - build
  - test
  - check
  - deploy

build:
  stage: build
  tags:
    - dockerex
  script: ./gradlew --build-cache assemble
  artifacts:
    paths:
      - build/libs/*.jar
      - build/distributions/*.tar
    expire_in: 1 day

test:
  stage: test
  tags:
    - dockerex
  script: ./gradlew test
  artifacts:
    reports:
      junit:
        - "build/test-results/test/TEST-*.xml"
    expire_in: 28 day

checkstyle:
  stage: check
  tags:
    - dockerex
  script: ./gradlew checkstyle
  artifacts:
    paths:
      - build/reports/checkstyle/main.html
    when: on_failure
    expire_in: 28 days

pmd:
  stage: check
  tags:
    - dockerex
  script: ./gradlew pmd
  artifacts:
    paths:
      - build/reports/pmd/*.html
    when: on_failure
    expire_in: 28 days

spotbugs:
  stage: check
  tags:
    - dockerex
  script: ./gradlew spotbugs
  artifacts:
    paths:
      - build/reports/spotbugs/*.html
    when: on_failure
    expire_in: 28 days

.deploy:
  stage: deploy
  tags:
    - dockerex
  # see https://docs.gitlab.com/ee/ci/docker/using_docker_build.html#tls-enabled
  # for image usage and settings for building with TLS and docker in docker
  image: docker:19.03.1
  services:
    - docker:19.03.1-dind
  variables:
    DOCKER_TLS_CERTDIR: "/certs"
  script:
    - DOCKER_TAG_NAME=$(echo $CI_COMMIT_REF_SLUG- | sed 's/^master-$//')
    - docker build --pull -t titan-ccp-anomaly-detection .
    - docker tag titan-ccp-anomaly-detection $DOCKERHUB_ORG/titan-ccp-anomaly-detection:${DOCKER_TAG_NAME}latest
    - docker tag titan-ccp-anomaly-detection $DOCKERHUB_ORG/titan-ccp-anomaly-detection:$DOCKER_TAG_NAME$(date +%Y%m%d%H%M%S)
    - docker tag titan-ccp-anomaly-detection $DOCKERHUB_ORG/titan-ccp-anomaly-detection:$DOCKER_TAG_NAME$CI_COMMIT_SHA
    - echo $DOCKERHUB_PW | docker login -u $DOCKERHUB_ID --password-stdin
    - docker push $DOCKERHUB_ORG/titan-ccp-anomaly-detection
  only:
    variables:
      - $DOCKERHUB_ORG
      - $DOCKERHUB_ID
      - $DOCKERHUB_PW
